server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: medecin-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/medecins/**
          filters:
            - RewritePath=/api/medecins/(?<segment>.*), /api/medecins/$\{segment}
            - AddRequestHeader=X-Gateway-Source, api-gateway
        - id: visite-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/visites/**
          filters:
            - RewritePath=/api/visites/(?<segment>.*), /api/visites/$\{segment}
            - AddRequestHeader=X-Gateway-Source, api-gateway

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    reactor.netty: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*" 